### ISSUE TITLE
adding the content on Terms & Conditions .

### ISSUE THREAD

**Issue by kratik1237** [MastanSayyad/Visual-Sort#100]
Description
We need to create a "Terms & Conditions" page for our website. This page should clearly outline the terms of use for our services, including user responsibilities, prohibited activities, and legal disclaimers. The page should be designed to provide clear and concise information to our users regarding the terms under which they are allowed to use our services.

Use Case
The "Terms & Conditions" page is essential for:

Informing users about their responsibilities and rights while using our services.
Protecting the company legally by defining prohibited activities and disclaimers.
Enhancing trust and transparency with our users by providing clear usage guidelines.
Benefits include:

Reduced risk of legal disputes by having clear terms in place.
Improved user trust and credibility.
Ensuring compliance with legal requirements.

**Comment by kratik1237** [comment]
@MastanSayyad assign me .

**Comment by kratik1237** [comment]
![Screenshot (40)](https://github.com/user-attachments/assets/3b7ec8dc-4aec-45c5-994d-971f9a3ecb90)
@MastanSayyad ???

**Comment by kratik1237** [comment]
![Screenshot (40)](https://github.com/user-attachments/assets/6e1f17c3-469b-4913-82f1-b6a8a31be604)
@MastanSayyad

**Comment by MastanSayyad** [comment]
> @MastanSayyad assign me .

It is already assigned!! @kratik1237 in #85 
please check some other issues

**Comment by MastanSayyad** [comment]
> ![Screenshot (40)](https://private-user-images.githubusercontent.com/142149999/348363798-6e1f17c3-469b-4913-82f1-b6a8a31be604.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA4MTA2OTEsIm5iZiI6MTcyMDgxMDM5MSwicGF0aCI6Ii8xNDIxNDk5OTkvMzQ4MzYzNzk4LTZlMWYxN2MzLTQ2OWItNDkxMy04MmYxLWI2YThhMzFiZTYwNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcxMlQxODUzMTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00OWI5YzI1N2RmNjRjZjY3Y2I1YTdhOTEwZDA2MWU1YTRlMDdlMjdiNzc1YmZlM2FhZDdiNzcxMTBkNzUwYjZjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.HYzYMBEyRyCTo0IFdn5lfsFiAsF9DnD0eIKym-p0CIY) @MastanSayyad

You can ignore it is just github action workflow
