### ISSUE TITLE
Create "Licensing" Page

### ISSUE THREAD

**Issue by kratik1237** [MastanSayyad/Visual-Sort#101]
Description
We need to create a "Licensing" page for our website. This page should provide detailed information about the licenses under which our products, services, and content are released. The page should clearly outline the terms and conditions for both open-source and commercial licenses, as well as any third-party licenses we utilize.

Use Case
The "Licensing" page is necessary for:

Informing users about the licensing terms for using our products and services.
Ensuring compliance with open-source and commercial license requirements.
Providing clear guidelines on how our content can be used and distributed.
Benefits include:

Clear communication of licensing terms to avoid misuse.
Legal protection by specifying the terms of use for our intellectual property.
Transparency with users and developers about the licenses that apply to our products.

**Comment by kratik1237** [comment]
@MastanSayyad assign me.

**Comment by MastanSayyad** [comment]
@kratik1237 It is already assigned to someone else!! in Issue #85
