### ISSUE TITLE
[BUG] Copyright Year

### ISSUE THREAD

**Issue by Meetjain1** [MastanSayyad/Visual-Sort#105]
**Description**
Currently copyright year is the direct copy paste of text , It should fetch the current year instead of it . @MastanSayyad assign this issue to me I will fix it , I am working under VSOC. Thanks

**Use Case**
(Use cases and benefits)

**Screenshots**
(Screenshots of the issue or reference)

**Additional Context**
(Any other context about the problem)

**Comment by MastanSayyad** [comment]
@Meetjain1 assigned to you!
Also can you replace my name with Visual Sort 

![image](https://github.com/user-attachments/assets/48f154d4-4c43-4f49-924c-98f62b15f1c1)
