### ISSUE TITLE
 Add counting sort in the list of sorting techniques

### ISSUE THREAD

**Issue by kratik1237** [MastanSayyad/Visual-Sort#108]
**Description**
We need to add Counting Sort to our existing list of sorting techniques in our documentation/codebase. Counting Sort is a non-comparison-based sorting algorithm that sorts elements in linear time complexity for a specific range of input.

**Use Case**
- Enhances our sorting algorithm collection
- Provides an efficient sorting method for integers or objects with integer keys
- Useful for educational purposes to demonstrate different sorting paradigms
- Can significantly improve performance in scenarios with a limited range of input values

**Comment by kratik1237** [comment]
@MastanSayyad I AM WORKING ON IT pls reopen the issue

**Comment by MastanSayyad** [comment]
@kratik1237 You should have let me now about it before starting working in it, I would have allowed you

Nevermind, Show me the work progress!

**Comment by MastanSayyad** [comment]
After that I'll assign this issue to you!
