### ISSUE TITLE
dark mode switcher

### ISSUE THREAD

**Issue by tashi-tech** [MastanSayyad/Visual-Sort#12]
create dark mode switcher using
html
css
javascript

**Comment by MastanSayyad** [comment]
@tashi-tech assigned to you!!

**Comment by MastanSayyad** [comment]
much needed

**Comment by YashSherla** [comment]
can i attempt

**Comment by MastanSayyad** [comment]
yes sure @YashSherla

**Comment by MastanSayyad** [comment]
@YashSherla are you there?

**Comment by kratik1237** [comment]
I am interested @MastanSayyad

**Comment by RadhikaMalpani1702** [comment]
@kratik1237 Assigned to you, go ahead

**Comment by kratik1237** [comment]
@RadhikaMalpani1702 @MastanSayyad  Dark mode button are working plz check PR

**Comment by kratik1237** [comment]
@MastanSayyad  #12 issue

**Comment by kratik1237** [comment]
Dark mode switcher #12 issue
@MastanSayyad

**Comment by MastanSayyad** [comment]
Yes, what about that?  #12 issue is assign to you right?

**Comment by kratik1237** [comment]
Mene pr generate kr diya hai @MastanSayyad

**Comment by MastanSayyad** [comment]
![Screenshot_2024-07-12-21-16-15-75_320a9a695de7cdce83ed5281148d6f19.jpg](https://github.com/user-attachments/assets/584c6afd-1b63-4874-b86c-8e3bfb26ebfe)

There is no PR genrated for #12 issue!!

**Comment by MastanSayyad** [comment]
Can you please send me the link of the PR you generated?

**Comment by kratik1237** [comment]
Okay

**Comment by kratik1237** [comment]
Please check @MastanSayyad

**Comment by kratik1237** [comment]
Pr@MastanSayyad
