### ISSUE TITLE
making counting sort page dynamic and responsive

### ISSUE THREAD

**Issue by Aaryanb45** [MastanSayyad/Visual-Sort#125]
I will make this sorting page as other sorting pages because it is looking odd
I will make it responsive 
I will add counting sort card in index page
Improve footer and navbar

**Comment by MastanSayyad** [comment]
> I will make this sorting page as other sorting pages because it is looking odd I will make it responsive I will add counting sort card in index page Improve footer and navbar

Contributo is Already working on it! lets wait till he finishes!

**Comment by MastanSayyad** [comment]
Yes you can i will let you know till afternoon

**Comment by MastanSayyad** [comment]
@Aaryanb45 I will add bonus after the work is done
