### ISSUE TITLE
[BUG] Fix mergesort navlink and bubblesort css

### ISSUE THREAD

**Issue by vansh-codes** [MastanSayyad/Visual-Sort#134]
**Description**
(Description about the issue)

- mergesort page is not available after going to a algorithm as its href is wrong in the code, i would love to fix it for every page where its not available
- Ex to verify: go to `Algorithm` in the navbar, select `Bubble Sort` from the dropdown, now on the BubbleSort page again go on `Algorithm` in the navbar and select `mergesort` :: now its not available
- Bubble Sort page algorithm description is not visible correctly, I would fix that
- Add `faivon` on every page, its missing on algorithm pages (check here: https://visual-sort-pink.vercel.app/Algorithm/Bubble.html)

**Use Case**
(Use cases and benefits)
- page availability

**Screenshots**
(Screenshots of the issue or reference)
![image](https://github.com/user-attachments/assets/6b7c00f3-3d1f-499b-a000-612835e310db)

![image](https://github.com/user-attachments/assets/efa8ea09-2cba-4d19-89f6-47d0f00522e8)

**Additional Context**
(Any other context about the problem)

**Comment by MastanSayyad** [comment]
I was planning to solve it myself, but you can go ahead @vansh-codes
