### ISSUE TITLE
Terms and condition

### ISSUE THREAD

**Issue by Shrutibansal22** [MastanSayyad/Visual-Sort#138]
@MastanSayyad 
I wanted to change the UI of terms and condition page.As its styling is far far different from ur webiste.

**Screenshots**
![image](https://github.com/user-attachments/assets/266e6fa1-0b9e-4be9-9626-f8c17a838199)

Kindly assign me this issue uner hacktobree-fest 2024

**Comment by MastanSayyad** [comment]
Much needed @Shrutibansal22
