### ISSUE TITLE
Add counting sort in the list of sorting techniques 

### ISSUE THREAD

**Issue by Kaustav2410** [MastanSayyad/Visual-Sort#14]

**Comment by MastanSayyad** [comment]
Add more context with screenshots @Kaustav2410

**Comment by Kaustav2410** [comment]
Short Description in HomePage 
Proper Responsive WebPage dedicated to Counting sort
Video Lectures: Learn the concept visually with video tutorials.
Concise Notes: Grasp the core principles with clear and focused notes.
Interactive Code: Experiment and delve deeper with implemented code examples.
Practice Problems: Test your understanding with challenging questions.
Performance Analysis: Discover Counting Sort's time and space efficiency.

**Comment by MastanSayyad** [comment]
@Kaustav2410 any progress??

**Comment by kratik1237** [comment]
I am interested @MastanSayyad assign me .

**Comment by kratik1237** [comment]
@MastanSayyad 
I am working on it.
why are you closed

**Comment by kratik1237** [comment]
@MastanSayyad ??

**Comment by MastanSayyad** [comment]
@kratik1237 I didn't assign you then why did you started the work? this is against the contributing guidelines of the program. 

also always keep remember that you can only work on the issue if it is assigned to you! 
The vsoc 24 is about to end and this issue is not planned for now, That's why I closed the issue!

**Comment by kratik1237** [comment]
okay... @MastanSayyad

**Comment by MastanSayyad** [comment]
@kratik1237 I can reopen it only if you show me how much work is progressed

**Comment by kratik1237** [comment]
![Uploading Screenshot (48).png…]()

**Comment by kratik1237** [comment]
I am improving it further @MastanSayyad

**Comment by MastanSayyad** [comment]
@kratik1237 It is not aligning with the other visulizers

![image](https://github.com/user-attachments/assets/0b0fbf82-f8de-46f0-9dd7-f7e2d900b3d6)

**Comment by kratik1237** [comment]
yes but i am working on it 
@MastanSayyad

**Comment by MastanSayyad** [comment]
@kratik1237 Any deadline? as tomorrow 16th july is the last day of VsoC after that I cant assign you the points as the Vsoc system will close by tomorrow 17th July 12:00AM

**Comment by kratik1237** [comment]
today i will submit you @MastanSayyad

**Comment by MastanSayyad** [comment]
I assigned it to you! but know that if the co-admin doesn't approve the changes then I have to close it again! bcoz consistency across all the pages is necessary!

**Comment by kratik1237** [comment]
@MastanSayyad Thanks

**Comment by kratik1237** [comment]
today 5PM i will submit you ,can you give me points or not ?? if co admine doesn't approve? @MastanSayyad

**Comment by MastanSayyad** [comment]
> today 5PM i will submit you ,can you give me points or not ?? if co admine doesn't approve? @MastanSayyad

Obviously for your time and efforts I will assign some points to you!

**Comment by kratik1237** [comment]
thankyou @MastanSayyad

**Comment by MastanSayyad** [comment]
> Short Description in HomePage Proper Responsive WebPage dedicated to Counting sort Video Lectures: Learn the concept visually with video tutorials. Concise Notes: Grasp the core principles with clear and focused notes. Interactive Code: Experiment and delve deeper with implemented code examples. Practice Problems: Test your understanding with challenging questions. Performance Analysis: Discover Counting Sort's time and space efficiency.

Also the bonus label is for all these functionalities only! if you are going to add visiuilizer only then I have to label it accordingly!
And please make sure your code does not broke the UI of the website

**Comment by kratik1237** [comment]
SURE I FOLLOW THIS POINTS @MastanSayyad
