### ISSUE TITLE
[FEATURE] : Enhance ui of the terms and conditions page

### ISSUE THREAD

**Issue by aditya-bhaumik** [MastanSayyad/Visual-Sort#143]
**Description**
improve the ui of the terms and conditions page

**Use Case**
(Use cases and benefits)

**Screenshots**
(Screenshots of the issue or reference)
![image](https://github.com/user-attachments/assets/dcfac960-bb03-4389-8e88-1899d0b08016)

**Additional Context**
(Any other context about the problem)

**Comment by MastanSayyad** [comment]
This one is not needed as it was changed just recently.
