### ISSUE TITLE
[BUG] Navigation tab highlight mismatch error.

### ISSUE THREAD

**Issue by NagaJahnaviD** [MastanSayyad/Visual-Sort#152]
Hello @MastanSayyad sir,
I noticed an issue with the navigation bar: 
the highlighting of the nav tab text does not update according to the page in view. 
Although it's a minor issue, fixing it would enhance the user experience. 

https://github.com/user-attachments/assets/215880ac-bf6e-4b36-a345-01d87a176d9f

**Comment by MastanSayyad** [comment]
Assigned

**Comment by pranjalsingh03** [comment]
I would like to take ownership of resolving this bug. Please assign this task to me.

**Comment by MastanSayyad** [comment]
nope it's fine, you can go on, I have assigned you!

**Comment by pranjalsingh03** [comment]
i have created the pr please check it
