### ISSUE TITLE
[BUG] Fix the href anchor tags in the footer section to link to the correct pages & sections.

### ISSUE THREAD

**Issue by krittika019** [MastanSayyad/Visual-Sort#156]
**Description**
(Description about the issue)
1. In the footer section of the home page, when clicked on the "Home" link currently not direct users to the intended "Home" section. Similarly with the "Contact" link.

2. In the footer section of the privacy-policy page, all the links except "Terms & Conditions" and "privacy-policy" link not directs users to the indented sections & page.

3.  In the footer section of the Terms & Conditions page, all the links except "privacy-policy" and "Terms & Conditions" link not directs users to the indented sections & page.

4.  In the footer section of the Licensing page, all the links except "privacy-policy" and "Terms & Conditions" link not directs users to the indented sections & page.

**Use Case**
(Use cases and benefits)
Fixing link issues across pages ensures users can easily navigate to all relevant sections and pages, providing a seamless and consistent browsing experience. 

**Screenshots**
(Screenshots of the issue or reference)

https://github.com/user-attachments/assets/8438d62a-bfa8-48c6-a2a7-30a2c561514b

**Comment by MastanSayyad** [comment]
@krittika019 assigned
