### ISSUE TITLE
Github issue template and Auto commenting after creating an issue 

### ISSUE THREAD

**Issue by MastanSayyad** [MastanSayyad/Visual-Sort#17]
Need Github Auto commenting feature when someone create an issue as a welcome and thank you message the message should also contain to read my CONTRIBUTING.md file and star the repo before contributing 

After clicking on new issue there should three sections

1) Bug Report 🐞
2) Feature Request 💡 
3) Documentation 📄 

Each of the section should have following sections

### Description

(Description about issue) 

### Use case

(Use cases and benefits) 

### Screenshots

(Screenshots of the issue or reference) 

### Additional context

**Comment by Mehak-Mattoo** [comment]
You can assign this issue to me :)
