### ISSUE TITLE
Landing Page Ui

### ISSUE THREAD

**Issue by Mehak-Mattoo** [MastanSayyad/Visual-Sort#2]
1. Make the landing page explain what the website is for.
2. Change the background image to a sorting algorithm one.
3. Add a navbar

**Comment by MastanSayyad** [comment]
Assigned it to you @Mehak-Mattoo Let me know if you need anything, Thank you for your contribution, Dont forgot to star the repo!

**Comment by Mehak-Mattoo** [comment]
Will do
