### ISSUE TITLE
Excessive Whitespace in Footer - Visual Disruption

### ISSUE THREAD

**Issue by rajdesai17** [MastanSayyad/Visual-Sort#23]
This issue reports excessive whitespace present at the bottom of the webpage's footer. This whitespace creates a visually unappealing layout and disrupts the overall design coherence.
![Uploading Screenshot 2024-06-25 154411.png…]()

**Comment by MastanSayyad** [comment]
@rajdesai17 someone already assigned for it, pls cgdck for other issues!

**Comment by MastanSayyad** [comment]
@rajdesai17 assigned it to you

**Comment by MastanSayyad** [comment]
@rajdesai17 



changes you have to do are:

- Remove the excessive whitespacing of footer

![image](https://github.com/MastanSayyad/Visual-Sort/assets/101971980/8424a0d6-2e82-44ae-b42d-f921670cebcc)

- add transform: scale(1.2) hover to the links  

![image](https://github.com/MastanSayyad/Visual-Sort/assets/101971980/5c051bff-6b91-4398-8716-8f367269898b)

- Add links to my social icons , only for Linkdin and Github 

![image](https://github.com/MastanSayyad/Visual-Sort/assets/101971980/de7decba-ce0a-47aa-9683-11fbea5bc512)




Have you understand the task?? @rajdesai17

**Comment by rajdesai17** [comment]
yes
