### ISSUE TITLE
Feature: Adding Radix Sort in Visual Sort

### ISSUE THREAD

**Issue by AkshatPandey-2004** [MastanSayyad/Visual-Sort#27]
Hey !! 
i m Going to add Radix Sort in Visual Sort!!!!

pls label it as Bonus

**Comment by MastanSayyad** [comment]
like what Functionalities you are going to add? after knowing that i can label it as bonus

**Comment by MastanSayyad** [comment]
@AkshatPandey-2004 any progress?

**Comment by kratik1237** [comment]
I am interested @MastanSayyad assign me.
