### ISSUE TITLE
Various sorting pages enhancement 

### ISSUE THREAD

**Issue by Ayushswirlon** [MastanSayyad/Visual-Sort#3]
The pages for sorting are not working properly and overall UI is also not visual appealing 
Changes that can be made 
• UI of all sorting pages can be improve 
• ensuring functioning of the pages 
• adding various effects for user experience

**Comment by MastanSayyad** [comment]
@Ayushswirlon go ahead, Ensure proper functioning of the sorting pages, Thank You!

**Comment by Ayushswirlon** [comment]
Hey @MastanSayyad some conflixte are coming in pr how can I resolve them

**Comment by Ayushswirlon** [comment]
Thanks broo
