### ISSUE TITLE
Adding Login And SignUp Page

### ISSUE THREAD

**Issue by AkshatPandey-2004** [MastanSayyad/Visual-Sort#35]
Hey I can Make Login And SignUp Page

**Comment by MastanSayyad** [comment]
Are you going to initilize backend for it?

**Comment by kratik1237** [comment]
I am interested in this issue please assign me @MastanSayyad

**Comment by MastanSayyad** [comment]
> I am interested in this issue please assign me @MastanSayyad 

thank you @kratik1237 but this issue is already assigned, kindly look for some other issues!

**Comment by kratik1237** [comment]
Okay @MastanSayyad

**Comment by MastanSayyad** [comment]
@kratik1237 if you can and Privacy Policy Page (which is empty in footer section) then raise the issue ill Assigned it to you!

**Comment by kratik1237** [comment]
Okay I do @MastanSayyad

**Comment by kratik1237** [comment]
Please assign me @MastanSayyad

**Comment by MastanSayyad** [comment]
Create a new issue for it, I'll assign it to you

**Comment by kratik1237** [comment]
Okay.
