### ISSUE TITLE
Add About us section to the home page

### ISSUE THREAD

**Issue by MastanSayyad** [MastanSayyad/Visual-Sort#4]
Add an About Us Section In the Home Page After Algorithms section and link it to the Navbar

![image](https://github.com/MastanSayyad/Visual-Sort/assets/101971980/f7b2c036-efa7-4b6a-8104-4cf80f820094)

![image](https://github.com/MastanSayyad/Visual-Sort/assets/101971980/9daef8cb-eea0-4e42-a8f3-9258b4c9e211)

**Comment by YashSherla** [comment]
can i attempt

**Comment by YashSherla** [comment]
done

**Comment by YashSherla** [comment]
i have made pull req

**Comment by MastanSayyad** [comment]
you cant create a pull request about an issue unless it is assigning it to you

**Comment by MastanSayyad** [comment]
Can you create an About Us section below the Algorithms section? if yes then only I can assign it to you

**Comment by pandey22** [comment]
> Can you create an About Us section below the Algorithms section? if yes then only I can assign it to you

I would love to work on that @MastanSayyad  , please assign me the issue if possible

**Comment by MastanSayyad** [comment]
yeah sure @pandey22 assigned it to you, please make sure you add the section and link it to the navbar and in footer, thank you!!

**Comment by MastanSayyad** [comment]
@YashSherla i have assigned the issue to @pandey22, kindly raise another issue also i have merged your previous PR as it was just a minor change

**Comment by YashSherla** [comment]
ok @MastanSayyad
