### ISSUE TITLE
Adding comparision of Algorithm Feature

### ISSUE THREAD

**Issue by SivaBalaji-AR** [MastanSayyad/Visual-Sort#41]
we can Display comparision of working of two different algorithms and display its stats like time complexity , number of swaps , efficiency in current situation . (From Vsoc'24)

**Comment by MastanSayyad** [comment]
If yes then i can add bonus points for it according to the work!

**Comment by SivaBalaji-AR** [comment]
yes i can add time complexity , but how the comparision should be , like parallel display is fine??

**Comment by SivaBalaji-AR** [comment]
yes , i can add time complexity , but how the comparision should be exactly .

**Comment by MastanSayyad** [comment]
@SivaBalaji-AR  I dont have any idea regarding it but you can add a table to showcase comparison between sorting algos like best case worst case average case complexity and space complexity like this:

![1_8Wh8KHhTWlhKOd8fvNCl1A.jpg](https://github.com/MastanSayyad/Visual-Sort/assets/101971980/388af47e-fe90-4850-9671-946c03d468e9)

And you can a separate page describing the comparisons

Like for
- Comparsion Based Sorting Algorithms
- Non comparison based sorting algorithms

You can refer this page

https://www.cs.usfca.edu/~galles/visualization/ComparisonSort.html

Make sure you follow the website design theme for colors background, tables, fonts etc

Thats all i can suggest as visual representation are already present in our website 

If you have any idea then do let me know
