### ISSUE TITLE
Footer Needs Enhancements

### ISSUE THREAD

**Issue by MastanSayyad** [MastanSayyad/Visual-Sort#5]
As you can see the current footer is not much impressive

![image](https://github.com/MastanSayyad/Visual-Sort/assets/101971980/2149d229-03c6-46c9-b83d-f8d811d50a20)

Make enhancements and redesign the footer Make sure it contains all necessary contents

**Comment by Prakash-Raut** [comment]
Hi , I would love to work on this issue.

Solution: Redesign the footer as of now.

![image](https://github.com/MastanSayyad/Visual-Sort/assets/82020300/6499f02b-56ba-4ca5-9d64-b207dbfdd1f6)

Question: Can we include another CSS library like Tailwind CSS?

**Comment by MastanSayyad** [comment]
Assigned @Prakash-Raut Please also add another list of section besides support list section named as "Legal" which contains Privacy Policy, terms and Conditions, Licensing 

About the CSS libaray, Yes you can add only if it does not break or crash the other website components

**Comment by Prakash-Raut** [comment]
tailwind css link through cdn is not used for production so can't use that.
Is this project using customized Bootstrap ?

**Comment by MastanSayyad** [comment]
Yes it is, if not you can add custom CSS or bootsrap @Prakash-Raut

**Comment by Prakash-Raut** [comment]
how about this one redesign again in bootstrap 

![image](https://github.com/MastanSayyad/Visual-Sort/assets/82020300/efcdad59-0890-40a8-9e93-f6a554ae665e)

should i make PR ?

**Comment by MastanSayyad** [comment]
- Make visual sort title little bold
- Below title add this description "Visual Sort is a web-based sorting algorithm visualization tool which provides an interactive way to visualize various sorting algorithms in action, helping users understand how different algorithms work and their efficiency in sorting data"
- Remove by Mr. Mastan Sayyad
- in copyright instead of department of computer science and eng. Add "Visual Sort - Mastan Sayyad"


Everything else looks good to me!

**Comment by MastanSayyad** [comment]
@Prakash-Raut after the changes you can make the PR
