### ISSUE TITLE
Bug-irregular functioning of submit button during visualisation

### ISSUE THREAD

**Issue by SivaBalaji-AR** [MastanSayyad/Visual-Sort#55]
https://github.com/MastanSayyad/Visual-Sort/assets/151618924/e97b7540-262e-4ad6-82a9-271e24d09c2e

we can solve this by , disabling submit button

The Reset button is also not working

**Comment by MastanSayyad** [comment]
Thank you for noticing @SivaBalaji-AR Assigned to you!

you can look for other issues or feature additions as well
