### ISSUE TITLE
adding Privacy Policy Page in footer 

### ISSUE THREAD

**Issue by kratik1237** [MastanSayyad/Visual-Sort#58]
please assign the issue @MastanSayyad

**Comment by MastanSayyad** [comment]
Privacy policy is already present in footer under legal section, you just have create a new privacy policy page and link it to the footer link @kratik1237 

Thing you have to do:
- Create Privacy Policy Page
- Link it to Footer 
- Page must be Responsive

**Comment by kratik1237** [comment]
@MastanSayyad

**Comment by kratik1237** [comment]
Points are not updated? @MastanSayyad

**Comment by MastanSayyad** [comment]
@kratik1237 points are updated pls check

**Comment by kratik1237** [comment]
Yes @MastanSayyad
