### ISSUE TITLE
Adding Student review section

### ISSUE THREAD

**Issue by Yaser-123** [MastanSayyad/Visual-Sort#6]
Adding this section using
HML
CSS
JS
making it responsive and adding rating to it

**Comment by MastanSayyad** [comment]
can you provide some more information? or reference Screenshot? @Yaser-123

**Comment by Yaser-123** [comment]
Sorry for late reply busy with college work

https://github.com/MastanSayyad/Visual-Sort/assets/140265777/236d4e61-0838-498a-ac5b-a4e1f8d3a21d

**Comment by mathushabai** [comment]
I can work on this if it is still up for grabs.

**Comment by MastanSayyad** [comment]
Looks great @Yaser-123 Assigned it to You!

**Comment by MastanSayyad** [comment]
> I can work on this if it is still up for grabs. 

Hey @mathushabai you can look for other issues as there are so many missing pages in website, and looking for new feature additions, please go through it and raise a new issue,  Thank You
