### ISSUE TITLE
Add comb sort to the algorithm list

### ISSUE THREAD

**Issue by aadium** [MastanSayyad/Visual-Sort#66]
Comb sort compares pairs of elements that are a certain distance apart, and swap them if they’re out of order. The distance between the pairs is initially set to the size of the list being sorted, and is then reduced by a shrink factor with each pass, until it reaches a minimum value of 1. This process is repeated until the list is fully sorted.

**Comment by aadium** [comment]
I am requesting you to assign me this issue.

**Comment by MastanSayyad** [comment]
@aadium there is already one for heap and quick sort integrated in visual.html file

and thank you for pointing that out, you can raise another issue to fix the navbar actually add visual.html in each link the links are of old files the visual.html file is the updated and integrated one with full visualized working functionality!!

**Comment by aadium** [comment]
I have created the pull request.
