### ISSUE TITLE
enhancing the login and signup button

### ISSUE THREAD

**Issue by Ayushswirlon** [MastanSayyad/Visual-Sort#76]
according to me the login button should be a pop up instead of a new page also person should have an option to switch from login to sign up directly and not to go through them in different website.

will also resolve the landing page issue in this

**Comment by RadhikaMalpani1702** [comment]
@Ayushswirlon What is the progress since it has been a week

**Comment by Ayushswirlon** [comment]
Had started working on it but currently has more issues to work on

**Comment by RadhikaMalpani1702** [comment]
@Ayushswirlon It's okay take your time
