### ISSUE TITLE
Making navbar relative to hero section

### ISSUE THREAD

**Issue by Mehak-Mattoo** [MastanSayyad/Visual-Sort#87]
**Description**
Making navbar as relevant to the hero section

**Use Case**
Making navbar in response to the hero section to improve the UI/UX for Hero section

**Screenshots**
![nhhhh](https://github.com/MastanSayyad/Visual-Sort/assets/77096365/1e748024-acdc-400e-b836-71125d970d1d)

**Additional Context**
(Any other context about the problem)

**Comment by MastanSayyad** [comment]
Please make seprate PRs for issues do not include multiple issues in one PR

**Comment by Mehak-Mattoo** [comment]
Sure
