### ISSUE TITLE
[BUG] : Signin Not working

### ISSUE THREAD

**Issue by Sudhanva21** [MastanSayyad/Visual-Sort#96]
**Description**
Sign-in in login page is not working

**Use Case**
(Use cases and benefits)

**Screenshots**

https://github.com/MastanSayyad/Visual-Sort/assets/123559895/f9131b11-4a12-4320-8b1a-dcf5abb8b973

**Additional Context**
Assign me this isseue. Working under VSoC '24.

**Comment by MastanSayyad** [comment]
@Sudhanva21 It's because it is a dummy Page, front end only!
please look for some other issues!
